# Generated by Django 5.1.3 on 2026-05-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
    ]
