# Generated by Django 5.1.3 on 2026-05-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата')], max_length=20, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt для изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (YouTube, Vimeo)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.blogpost', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Блок статьи',
                'verbose_name_plural': 'Блоки статей',
                'db_table': 'blog_blocks',
                'ordering': ['order', 'id'],
            },
        ),
    ]
