# Generated by Django 5.1.3 on 2026-05-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blogpost_blogblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание типа кожи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skin_types/')),
            ],
            options={
                'verbose_name': 'Тип кожи',
                'verbose_name_plural': 'Типы кожи',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('value', models.IntegerField(verbose_name='Числовое значение (вес)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='SkinCareRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_recommendations', to='api.product')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.skintype')),
            ],
            options={
                'verbose_name': 'Рекомендация товара',
                'verbose_name_plural': 'Рекомендации товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkinTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(verbose_name='Минимальный балл')),
                ('max_score', models.IntegerField(verbose_name='Максимальный балл')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.skintype')),
            ],
            options={
                'verbose_name': 'Правило определения',
                'verbose_name_plural': 'Правила определения',
            },
        ),
    ]
